name: pyscfad_env
channels:
  - defaults
dependencies:
  - python=3.9
  - pip=23.0
  - pip:
    - cmake>=3.18
    - numpy>=1.17
    - scipy<1.11
    - jax>=0.3.25
    - jaxlib>=0.3.25
    - typing_extensions
    - jaxopt>=0.2
    - -e git+https://github.com/fishjojo/pyscf.git@v2.1.1-ad#egg=pyscf
    - -e git+https://github.com/fishjojo/properties.git@ad#egg=pyscf-properties
