name: Build

on:
  release:
    types: [published]

jobs:
  build_wheels_x86:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, macos-12]

    steps:
      - uses: actions/checkout@v4

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.16.5
        env:
          CIBW_ARCHS_LINUX: "x86_64"
          CMAKE_CONFIGURE_ARGS: "-DWITH_F12=OFF"
        with:
          package-dir: pyscfadlib
          output-dir: pyscfadlib/wheelhouse
          config-file: "{package}/pyproject.toml"

      - uses: actions/upload-artifact@v4
        with:
          name: cibw-wheels-${{ matrix.os }}-${{ strategy.job-index }}
          path: pyscfadlib/wheelhouse/*.whl

  build_wheels_arm64:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-14]

    steps:
      - uses: actions/checkout@v4

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.16.5
        env:
          CMAKE_CONFIGURE_ARGS: "-DWITH_F12=OFF"
          CMAKE_OSX_ARCHITECTURES: arm64
        with:
          package-dir: pyscfadlib
          output-dir: pyscfadlib/wheelhouse
          config-file: "{package}/pyproject.toml"

      - uses: actions/upload-artifact@v4
        with:
          name: cibw-wheels-${{ matrix.os }}-${{ strategy.job-index }}
          path: pyscfadlib/wheelhouse/*.whl

