name: Build Doc

on:
  push:
    branches:
      - doc

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
      - name: install pyscf
        run: ./.github/workflows/install_pyscf.sh
      - name: build doc
        run: ./.github/workflows/build_doc.sh
