name: Publish pyscfad

on:
  release:
    types:
      - released
  workflow_dispatch:

jobs:
  publish_pypi_any:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: ["3.11"]

    environment: release
    permissions:
      id-token: write

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Build wheels
        run: |
            python3 -m pip install --upgrade build
            python3 -m build

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
