name: github release

on: [workflow_dispatch]

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Release Info
        run: ./.github/workflows/release_info.sh
        id: release_info
      - name: Create Release
        if: ${{ steps.release_info.outputs.version_tag }}
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.release_info.outputs.version_tag }}
          release_name: pyscfad release ${{ steps.release_info.outputs.version_tag }}
          body_path: RELEASE.md
          prerelease: true
          # draft: true
